### ISSUE TITLE
Error when match a global intent within component delegation

### ISSUE THREAD

**Issue by jrglg** [jovotech/jovo-framework#1049]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [X] Other... Please describe: Could be a bug, but I'm not sure

Having a simple Jovov4 project like this:
en.json
```
{
  "invocation": "my test app",
  "version": "4.0",
  "intents": {
    "YesIntent": {
      "phrases": [
        "yes",
        "yes please",
        "sure"
      ]
    },
    "NoIntent": {
      "phrases": [
        "no",
        "no thanks"
      ]
    },
    "GlobalIntent": {
      "phrases": [
        "go to global intent"
      ]
    }
  }
}
```
GlobalComponent.ts
```
import { Component, BaseComponent, Global, Intents, PrioritizedOverUnhandled } from '@jovotech/framework';
import { LoveHatePizzaComponent } from './LoveHatePizzaComponent';
import { AnotherComponent } from './AnotherComponent';

@Global()
@Component({
  components: [AnotherComponent],
})
export class GlobalComponent extends BaseComponent {


  /**
   * 
   * For testing:
   * 1. Launch
   * 2. go to global intent
   * 3. look the error in the log
   */

  LAUNCH() {
    return this.$delegate(AnotherComponent, {
      resolve: {
        TEST: this.redirectToPizzaComponent
      }
    });
  }

  redirectToPizzaComponent() {
    return this.$redirect(LoveHatePizzaComponent);
  }

  @Intents(['GlobalIntent'])
  @PrioritizedOverUnhandled(true)
  foo() {
    // this way doesn't work as never reaches thisIsNeverEntered()
    return this.$delegate(AnotherComponent, {
      resolve: {
        TEST: this.thisIsNeverEntered
      }
    });

    // but this way does
    //return this.thisIsNeverEntered();
  }

  thisIsNeverEntered() {
    // I had this specific redirect: return this.$redirect(MyComponent, 'bar');
    // but replaced it to simplify:
    return this.$redirect(LoveHatePizzaComponent);
  }
}
```
And all the default files of a .ts default template

## Expected Behavior
When doing these steps from Jovo Debugger:

1.LAUNCH
2.GlobalIntent

It should redirect to LoveHatePizzaComponent (the component doesn't matter, it's just an example).
Note that the error says there's no `thisIsNeverEntered` method in `LoveHatePizzaComponent`, but it's not related with the redirect of `thisIsNeverEntered()`. I think it should look for the method in the GlobalComponent class instead. Am I mistaken?

## Current Behavior
An error is thrown.

### Error log
```
(node:17720) UnhandledPromiseRejectionWarning: HandlerNotFoundError: Could not find handler thisIsNeverEntered in component LoveHatePizzaComponent.
    at ComponentTreeNode.executeHandler (*omited*testglobalintent\node_modules\@jovotech\framework\src\ComponentTreeNode.ts:68:13)
    at Proxy.$resolve (*omited*testglobalintent\node_modules\@jovotech\framework\src\Jovo.ts:409:33)
    at AnotherComponent.START (*omited*testglobalintent\src\components\AnotherComponent.ts:10:17)
    at ComponentTreeNode.executeHandler (*omited*testglobalintent\node_modules\@jovotech\framework\src\ComponentTreeNode.ts:71:46)
    at Proxy.$delegate (*omited*testglobalintent\node_modules\@jovotech\framework\src\Jovo.ts:377:25)
    at GlobalComponent.foo (*omited*testglobalintent\src\components\GlobalComponent.ts:25:17)
    at ComponentTreeNode.executeHandler (*omited*testglobalintent\node_modules\@jovotech\framework\src\ComponentTreeNode.ts:71:46)
    at HandlerPlugin.handle (*omited*testglobalintent\node_modules\@jovotech\framework\src\plugins\HandlerPlugin.ts:55:25)
    at Array.<anonymous> (*omited*testglobalintent\node_modules\@jovotech\framework\src\plugins\HandlerPlugin.ts:24:19)
    at Middleware.run (*omited*testglobalintent\node_modules\@jovotech\framework\src\Middleware.ts:23:24)
```

## Your Environment
Default .ts project generated with @jovotech/cli: 4.0.0-beta.6 

Jovo packages of the current project :
  - @jovotech/filebuilder: 0.0.1

Environment:
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD

**Comment by jankoenig** [comment]
Thank you. Could you share the `$state` after the delegation happened?

**Comment by jrglg** [comment]
```
        "state": [
          {
            "component": "LoveHatePizzaComponent"
          }
        ],
```

**Comment by m-ripper** [comment]
Could you please share the `AnotherComponent`? Maybe the error is occurring there.

**Comment by jankoenig** [comment]
> ```
>         "state": [
>           {
>             "component": "LoveHatePizzaComponent"
>           }
>         ],
> ```

Thanks! Could you also share what the `$state` looks like before that?

**Comment by jrglg** [comment]
Sure:
```
import { Component, BaseComponent } from '@jovotech/framework';

@Component()
export class AnotherComponent extends BaseComponent {

  static readonly TEST: string = 'TEST';


  START() {
    return this.$resolve(AnotherComponent.TEST);
  }
}
```

**Comment by jrglg** [comment]
Here is the full exampl
[test global intent when redirecting.zip](https://github.com/jovotech/jovo-framework/files/7246479/test.global.intent.when.redirecting.zip)
e

**Comment by jrglg** [comment]
state is always this in the response:
```
"state": [
          {
            "component": "LoveHatePizzaComponent"
          }
 ],
```

**Comment by jrglg** [comment]
that example has async/await in AnotherComponent but it doesn't matter. that was a last try

**Comment by m-ripper** [comment]
Hey @jrglg,
thanks for your example project, with it, I was able to reproduce the issue and implement a fix. 
Your example project should work with the next update.

**Comment by jrglg** [comment]
Nice! Thank you!
