### ISSUE TITLE
Error: Missing required argument #1

### ISSUE THREAD

**Issue by ivanoterouvigo** [jovotech/jovo-framework#1521]
## I'm submitting a

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior

I would like to install and use the jovo framework.
I followed get started steps but it doesn't work.

### Error Log

```
11732 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
11732 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
11732 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
11732 verbose stack     at /usr/share/npm/lib/install/deps.js:457:7
11732 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
11732 verbose stack     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
11732 verbose stack     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
11732 verbose stack     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
11732 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
11732 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
11733 verbose cwd /home/ivan/007_coding
11734 error Linux 5.4.0-136-generic
11735 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@jovotech/cli"
11736 error node v8.10.0
11737 error npm  v3.5.2
11738 error code EMISSINGARG
11739 error typeerror Error: Missing required argument #1
11739 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
11739 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
11739 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
11739 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
11739 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
11739 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
11739 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
11739 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
11739 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
11739 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
11740 error typeerror This is an error with npm itself. Please report this error at:
11740 error typeerror     <http://github.com/npm/npm/issues>
11741 verbose exit [ 1, true ]
```

## Your Environment

- Jovo Framework version used: 4.x.x
- Operating System: Ubuntu
![image](https://user-images.githubusercontent.com/11814769/213281891-2674026b-a58e-49fc-b413-19fdd95531b0.png)

**Comment by jankoenig** [comment]
Hey! Looks like you're using Node `v8.10.0`. I recommend upgrading to Node `v16`
