### ISSUE TITLE
getPrevSpeech - TypeError: Cannot read property 'response' of undefined

### ISSUE THREAD

**Issue by kouz75** [jovotech/jovo-framework#266]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior
on several  DialogFlow projects sometime, following code crash:
    'Default Fallback Intent': function() {
        let speech = this.user().getPrevSpeech(0);
    },

The bug only appear randomly on production and I'm not able to reproduce it.

### Error log
```
2018-10-17T19:33:37.319Z 8b14869e-d243-11e8-9ad8-db4ed0d76681 TypeError: Cannot read property 'response' of undefined
at GoogleActionUser.getPrevSpeech (/var/task/node_modules/jovo-framework/lib/user.js:477:41)
at Jovo.Unhandled (/var/task/app/handlers/welcome.js:101:34)
```

Checking the value of this.context.prev can fix the crash. but why the context is empty ?

## Your Environment

* Jovo Framework version used: 1.4.12
* Operating System: AWS Lambda

**Comment by jankoenig** [comment]
The context is empty for new users, is it possible that new users somehow end up in the Default Fallback Intent through deep invocations?

**Comment by jankoenig** [comment]
Closing this for now. Feel free to reopen it if you run into the problem again.

**Comment by QuentinDela** [comment]
This issue is still happening for me with Jovo V2 on Google. 
I am wondering if it's because the userId is not consistent on AoG and this info is only saved in the DB.
One workaround might be to pass this info in the session variable.

**Comment by jankoenig** [comment]
Thanks @QuentinDela . The problem with the inconsistent user IDs will be fixed with the next update.

Interesting idea though: We could allow the configuration for people to choose whether they want context information stored in the database (`this.$user.$context`) or in the session data `this.$session.$context`. The latter might even make more sense for many use cases.

Will discuss this with @aswetlow

**Comment by mderrien29** [comment]
We needed something very similar in our project, might be interesting adding it to Jovo. Here's what we are using currently.

```
import { Plugin, PluginConfig, BaseApp, HandleRequest } from "jovo-core";

interface Config extends PluginConfig {

}

export class PrevSpeechWithoutDb implements Plugin {

    config: Config = {
        // default
    };

    constructor() {}

    install(app: BaseApp) {
        app.middleware("platform.output").use(this.saveSpeech.bind(this));
        app.middleware("router").use(this.replaceGetPrevSpeech.bind(this));
    }

    uninstall() {

    }

    saveSpeech(handleRequest: HandleRequest) {
        let speech = handleRequest.jovo.$response.getSpeech();
        handleRequest.jovo.$session.$data.lastReponse = speech;
    }

    replaceGetPrevSpeech(handleRequest: HandleRequest) {
        handleRequest.jovo.$user.getPrevSpeech = (i):string => {
            return handleRequest.jovo.$session.$data.lastReponse;
        };
    }
}
```

**Comment by aswetlow** [comment]
Thank you for sharing, @mderrien29

**Comment by aswetlow** [comment]
Closing this due to inactivity
