### ISSUE TITLE
running Jovo v2 on AWS Lambda  with DynamoDBB failed.

### ISSUE THREAD

**Issue by kouz75** [jovotech/jovo-framework#312]
## I'm submitting a...

- [ x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior
Running jovo v2 with DynamoDB enable on AWS Lambda failed with following error 
```
Error: Couldn't use DynamoDb. tableName has to be set. at DynamoDb.load (/var/task/node_modules/jovo-db-dynamodb/src/DynamoDb.ts:68:19) at JovoUser.loadDb (/var/task/node_modules/jovo-framework/src/middleware/user/JovoUser.ts:285:50) at Middleware.run (/var/task/node_modules/jovo-core/src/Middleware.ts:69:30) at App.hand
2018-12-28T11:02:37.348Z 15351718-0a90-11e9-94e9-4988bf0cde2d Error: Couldn't use DynamoDb. tableName has to be set.
at DynamoDb.load (/var/task/node_modules/jovo-db-dynamodb/src/DynamoDb.ts:68:19)
at JovoUser.loadDb (/var/task/node_modules/jovo-framework/src/middleware/user/JovoUser.ts:285:50)
at Middleware.run (/var/task/node_modules/jovo-core/src/Middleware.ts:69:30)
at App.handle (/var/task/node_modules/jovo-core/src/BaseApp.ts:111:49)
at <anonymous>
```
The same project works correctly with dynamodb when it's launch with jovo cli.

config file:
```
module.exports = {
    logging: false,
    intentsToSkipUnhandled: [
....
    ],
    intentMap: {
  ...
    },
    i18n: {
        fallbackLng: 'fr-FR',
        load: 'all',
        returnObjects: true,
    },
    db: {
        DynamoDb:{
            tableName: 'xxxx',
            awsConfig: {
                region: "eu-west-1",
            }
        }
    },
    user: {
        context: true
    }
 };
```

## Your Environment

* Jovo Framework version used: 2.0.3

**Comment by kouz75** [comment]
following doc https://www.jovo.tech/docs/installation/v1-migration#project-structure
config.js file should be in src folder (which works with jovo cli)
adding config.js in the root folder fix the issue with lambda function

**Comment by jankoenig** [comment]
Hi @kouz75, how did you deploy to AWS Lambda? You can create a deployment-ready zip file with `npm run bundle`, which should solve the issue. Take a look here: https://www.jovo.tech/docs/project-lifecycle#hosting

**Comment by jankoenig** [comment]
Added it to the migration guide as well. Hope this helps!
https://www.jovo.tech/docs/installation/v1-migration#deployment

**Comment by kouz75** [comment]
I'm using AWS CodeBuild to deploy to lambda with the following build spec (for jovo 1.X)

```
version: 0.2
phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      #- npm rebuild
      - npm install --save-prod
  pre_build:
    commands:
     - npm test
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml

```
I will check the doc to update my buildspec
