### ISSUE TITLE
Google Assistant Handler Routing Fails with Latest Update

### ISSUE THREAD

**Issue by jovofan** [jovotech/jovo-framework#412]
## I'm submitting a...

- [ X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Routing for Google Assistant platform handler has stopped working with latest JOVO updates.
Alexa Handler is working fine.
Sample Code Used for Unit Testing:
```
const handlers = {
    LAUNCH() {
        return this.toIntent('HelloWorldIntent');
    },
};

const alexaHandlers = {
    HelloWorldIntent() {
        this.tell('Hello Alexa User.');
    },
};

const googleAssistantHandlers = {
    HelloWorldIntent() {
        this.tell('Hello Google User.');
    },
};

app.setHandler(handlers);
app.setAlexaHandler(alexaHandlers);
app.setGoogleAssistantHandler
```

### Error log
```
Error -----------------------------------------------------------------
  
  Code:
  ERR_NO_ROUTE
  
  Message:
  Could not find the route "HelloWorldIntent" in your handler function.
  
  Stack:
  Error: Could not find the route "HelloWorldIntent" in your handler function.
      at Function.applyHandle (/home/jovo/HelloWorld/node_modules/jovo-framework/src/middleware/Handler.ts:202:19)
      at GoogleAction.jovo_core_1.Jovo.toIntent (/home/jovo/HelloWorld/node_modules/jovo-framework/src/middleware/Handler.ts:287:34)
      at GoogleAction.LAUNCH (/home/jovo/HelloWorld/src/app.js:44:21)
      at Function.applyHandle (/home/jovo/HelloWorld/node_modules/jovo-framework/src/middleware/Handler.ts:217:43)
      at handle (/home/jovo/HelloWorld/node_modules/jovo-framework/src/middleware/Handler.ts:46:23)
      at <anonymous>
  
   ----------------------------------------------------------------------
  
  
  Request details:
  this.$googleAction initialized
  this.$type: {"type":"LAUNCH"}
  this.$session.$data : {}
  this.$nlu : {}
  this.$inputs : {}
   
   ----------------------------------------------------------------------

```

## Your Environment

* Jovo Framework version used: 2.1
* Operating System: Ubuntu 16

**Comment by aswetlow** [comment]
Hey @jovofan 
This [PR](https://github.com/jovotech/jovo-framework/pull/410) by [kouz75](https://github.com/kouz75) fixed it. We will push it to NPM later today.

**Comment by jankoenig** [comment]
This should be fixed with the latest update. You can update with `jovo update` in your command line. Please reopen if the issue persists.

Btw, cool username!
