### ISSUE TITLE
Add default value to Firestore user updatedAt

### ISSUE THREAD

**Issue by kozikkam** [jovotech/jovo-framework#472]
## I'm submitting a...

- [ x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Saving a user to firestore without specifying updatedAt field should automatically set it to current date.

## Current Behavior
The application throws an error.

### Error log
```
  Stack:
  Error: Argument "data" is not a valid Document. Cannot use "undefined" as a Firestore value (found in field updatedAt).
      at Validator.(anonymous function).values [as isDocument] (/Users/user/Desktop/projects/chatbot-jovo/node_modules/@google-cloud/firestore/build/src/validate.js:92:27)
      at WriteBatch.set (/Users/user/Desktop/projects/chatbot-jovo/node_modules/@google-cloud/firestore/build/src/write-batch.js:225:25)
      at DocumentReference.set (/Users/user/Desktop/projects/chatbot-jovo/node_modules/@google-cloud/firestore/build/src/reference.js:340:27)
      at Firestore.save (/Users/user/Desktop/projects/chatbot-jovo/node_modules/jovo-db-firestore/src/Firestore.ts:147:22)
      at JovoUser.saveDb (/Users/user/Desktop/projects/chatbot-jovo/node_modules/jovo-framework/src/middleware/user/JovoUser.ts:432:21)
      at Middleware.run (/Users/user/Desktop/projects/chatbot-jovo/node_modules/jovo-core/src/Middleware.ts:85:30)
      at App.handle (/Users/user/Desktop/projects/chatbot-jovo/node_modules/jovo-core/src/BaseApp.ts:233:49)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Your Environment
* Jovo Framework version used: 2.2.1
* Jovo-db-firestore version used: 2.2.0

**Comment by KaanKC** [comment]
Hey Kamil,

I've found the bug. It will be fixed with the next release. Thanks 👍

**Comment by jankoenig** [comment]
Hi @kozikkam 👋 

This should be fixed after doing `jovo update`. If it doesn't work for you, please feel free to reopen.

Thanks!
