### ISSUE TITLE
errror for Google Assistant Option Items

### ISSUE THREAD

**Issue by AFRI4N** [jovotech/jovo-framework#564]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

With the Following an Object of OptionalItem, List and Carousel should be created

```
const { GoogleAssistant } = require('jovo-platform-googleassistant');

let itemOne = new GoogleAction.OptionItem();
let list = new GoogleAssistant.List();
let carousel = new GoogleAssistant.Carousel();
```

## Current Behavior

For the OptionItem:
```
Message:
GoogleAction is not defined

Stack:
ReferenceError: GoogleAction is not defined
```
x = List = Carousel :
```
Message:
GoogleAssistant.x is not a constructor

Stack:
TypeError: GoogleAssistant.x is not a constructor
```

### Error log
```
  Error -----------------------------------------------------------------

  Message:
  GoogleAssistant.List is not a constructor

  Stack:
  TypeError: GoogleAssistant.List is not a constructor
      at GoogleAction.getQuestionIntent (C:\Users\agr3756\Documents\Jovo-amsQuiz\src\app.js:704:20)
      at Function.applyHandle (C:\Users\agr3756\Documents\Jovo-amsQuiz\node_modules\jovo-framework\src\middleware\Handle
r.ts:195:43)
      at GoogleAction.jovo_core_1.Jovo.toIntent (C:\Users\agr3756\Documents\Jovo-amsQuiz\node_modules\jovo-framework\src
\middleware\Handler.ts:321:28)
      at GoogleAction.LAUNCH (C:\Users\agr3756\Documents\Jovo-amsQuiz\src\app.js:644:19)
      at Function.applyHandle (C:\Users\agr3756\Documents\Jovo-amsQuiz\node_modules\jovo-framework\src\middleware\Handle
r.ts:195:43)
      at handle (C:\Users\agr3756\Documents\Jovo-amsQuiz\node_modules\jovo-framework\src\middleware\Handler.ts:255:23)

   ----------------------------------------------------------------------


  Request details:
  this.$googleAction initialized
  this.$type: {"type":"LAUNCH"}
  this.$session.$data : {}
  this.$nlu : {}
  this.$inputs : {}


   ----------------------------------------------------------------------

  unhandledRejection

  TypeError: Cannot read property 'google' of undefined
      at GoogleAssistantDialogflowFactory.createResponse (C:\Users\agr3756\Documents\Jovo-amsQuiz\node_modules\jovo-plat
form-googleassistant\src\dialogflow\GoogleAssistantDialogflowFactory.ts:31:43)
      at DialogflowResponseBuilder.create (C:\Users\agr3756\Documents\Jovo-amsQuiz\node_modules\jovo-platform-dialogflow
\src\core\DialogflowResponseBuilder.ts:13:29)
      at Conversation.sendToServer (C:\Users\agr3756\Documents\Jovo-amsQuiz\node_modules\jovo-core\src\Conversation.ts:1
52:65)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  TypeError: Cannot read property 'google' of undefined
      at GoogleAssistantDialogflowFactory.createResponse (C:\Users\agr3756\Documents\Jovo-amsQuiz\node_modules\jovo-plat
form-googleassistant\src\dialogflow\GoogleAssistantDialogflowFactory.ts:31:43)
      at DialogflowResponseBuilder.create (C:\Users\agr3756\Documents\Jovo-amsQuiz\node_modules\jovo-platform-dialogflow
\src\core\DialogflowResponseBuilder.ts:13:29)
      at Conversation.sendToServer (C:\Users\agr3756\Documents\Jovo-amsQuiz\node_modules\jovo-core\src\Conversation.ts:1
52:65)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Your Environment

* Jovo Framework version used: 
```
Jovo CLI Version: 2.2.8

Jovo packages of current project:
  jovo-cms-i18next: 2.2.13
  jovo-core: 2.2.12
  jovo-db-filedb: 2.2.12
  jovo-framework: 2.2.15
  jovo-platform-alexa: 2.2.17
  jovo-platform-dialogflow: 2.2.13
  jovo-platform-googleassistant: 2.2.15
  jovo-plugin-debugger: 2.2.13
```
* Operating System: Windows 7

**Comment by aswetlow** [comment]
Oh, it's outdated in the docs.

Try this
```javascript
const { GoogleAssistant, OptionItem, List, Table } = require('jovo-platform-googleassistant');
```

```javascript
let table = new Table();
```

**Comment by AFRI4N** [comment]
Thanks that helped.

Does this also effekt the ON_ELEMENT_SELECTED() Intent?
Cause I can't get it triggered

**Comment by AFRI4N** [comment]
@aswetlow Thanks. You should also update it in the docs :grinning:
