### ISSUE TITLE
Botanalytics integration does not work with Google Assistant

### ISSUE THREAD

**Issue by mderrien29** [jovotech/jovo-framework#568]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Botanalytics should work for both platforms.

## Current Behavior
Botanalytics refuses to log requests for the google assistant.

### Error log

```
[2019-08-28 14:14:33] [LOG]    [Botanalytics] Error: Failed to log message Error: The request was unacceptable. This is often due to missing a required parameter. ERROR:[object Object]
    at Object.checkResponse (/root/projet/jovo/node_modules/botanalytics/util.js:41:28)
    at Request.request [as _callback] (/root/projet/jovo/node_modules/botanalytics/platforms/google.js:134:35)
    at Request.self.callback (/root/projet/jovo/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/projet/jovo/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/projet/jovo/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
```

Looking more closely at the response object in `node_modules/botanalytics`
```
[ '\'userId\' field(s) is/are required inside \'user\' parameter in json payload' ]
```

request object in `node_modules/botanalytics`
```
[nodejs] {url: '/messages/google-assistant/dialogflow/',
[nodejs]   method: 'POST',
[nodejs]   json: true,
[nodejs]   body: 
[nodejs]    { request: 
[nodejs]       { responseId: '2b347f59-c7ad-4b49-978e-12303ddfa6fb-ee1dc704',
[nodejs]         queryResult: 
[nodejs]          { queryText: 'GOOGLE_ASSISTANT_WELCOME',
[nodejs]            parameters: {},
[nodejs]            allRequiredParamsPresent: true,
[nodejs]            outputContexts: 
[nodejs]             [ {...}, {...}, ... ],
[nodejs]            intent: 
[nodejs]             { name: 'projects/.../agent/intents/4922b44d-6665-457d-8668-49cb2b76e6ec',
[nodejs]               displayName: 'Default Welcome Intent' },
[nodejs]            intentDetectionConfidence: 1,
[nodejs]            languageCode: 'fr' },
[nodejs]         originalDetectIntentRequest: 
[nodejs]          { source: 'google',
[nodejs]            version: '2',
[nodejs]            payload: 
[nodejs]             GoogleActionRequest {
[nodejs]               user: 
[nodejs]                { locale: 'fr-FR',
[nodejs]                  lastSeen: '2019-08-28T10:07:13Z',
[nodejs]                  idToken: '...',
[nodejs]                  userVerificationStatus: 'VERIFIED' },
[nodejs]               conversation: 
[nodejs]                { conversationId: 'ABwppHGgslF-cQwW55PSuOqmHaUeg3BpErPRFesFsiTIYSKFuSrYANCunxLUKfC_WQd1i2QaSsAfEDwkaAg',
[nodejs]                  type: 'NEW' },
[nodejs]               inputs: 
[nodejs]                [ { intent: 'actions.intent.MAIN',
[nodejs]                    rawInputs: 
[nodejs]                     [ { inputType: 'KEYBOARD',
[nodejs]                         query: 'Parler avec mon application test' } ] } ],
[nodejs]               surface: 
[nodejs]                { capabilities: 
[nodejs]                   [ { name: 'actions.capability.WEB_BROWSER' },
[nodejs]                     { name: 'actions.capability.AUDIO_OUTPUT' },
[nodejs]                     { name: 'actions.capability.ACCOUNT_LINKING' },
[nodejs]                     { name: 'actions.capability.MEDIA_RESPONSE_AUDIO' },
[nodejs]                     { name: 'actions.capability.SCREEN_OUTPUT' } ] },
[nodejs]               isInSandbox: true,
[nodejs]               requestType: 'SIMULATOR' } },
[nodejs]         session: 'projects/.../agent/sessions/ABwppHGgslF-cQwW55PSuOqmHaUeg3BpErPRFesFsiTIYSKFuSrYANCunxLUKfC_WQd1i2QaSsAfEDwkaAg' },
[nodejs]      response: 
[nodejs]       DialogflowResponse {
[nodejs]         fulfillmentText: '...',
[nodejs]         outputContexts: [],
[nodejs]         payload: 
[nodejs]          { google: 
[nodejs]             GoogleActionResponse {
[nodejs]               expectUserResponse: true,
[nodejs]               richResponse: 
[nodejs]                { items: 
[nodejs]                   [ { simpleResponse: 
[nodejs]                        { ssml: '...'} } ],
[nodejs]                  suggestions: 
[nodejs]                   [{...}, {...}] },
[nodejs]               noInputPrompts: 
[nodejs]                [ { ssml: '...'} ],
[nodejs]               userStorage: '{"userId":"..."}' } } } } }
```

## Your Environment
* Operating System: Ubuntu 18.04
* Typescript 3.4.5
```
"jovo-analytics-botanalytics": "^2.2.10",
"jovo-cms-googlesheets": "^2.2.12",
"jovo-framework": "^2.2.13",
"jovo-platform-alexa": "^2.2.15",
"jovo-platform-dialogflow": "^2.2.11",
"jovo-platform-googleassistant": "^2.2.13",
```

**Comment by mderrien29** [comment]
Also, relevant config.ts

```
module.exports = {
  analytics: {
    BotanalyticsAlexa: {
      key: "...",
    },
    BotanalyticsGoogleAssistant: {
      key: "...",
    },
  },
}
```

**Comment by aswetlow** [comment]
I can't find that check in the `botanalytics` module (version 2.4.8). What version do you use?

Could you check in `/node_modules/botanalytics/package.json` ?

**Comment by mderrien29** [comment]
currently using `"botanalytics@2.4.9"`

Also, it seems like the application is indeed reporting the google crawler requests.

**Comment by aswetlow** [comment]
Seems like Botanalytics haven't removed the server-side since Google Assistant got rid of the userId :/

**Comment by mderrien29** [comment]
Yes that looks like it's a screw up on their side. We already contacted them earlier today, so i'll update this if we get an update on the issue. 

Thank you !

**Comment by aswetlow** [comment]
Thanks!

**Comment by aswetlow** [comment]
hey @mderrien29 
Any news about it?

**Comment by mderrien29** [comment]
So, it's still not working, we did not get a response for weeks now and we are going to switch to another jovo integration, `dashbot.io`.

**Comment by aswetlow** [comment]
😞 

Thanks for the update.

**Comment by jankoenig** [comment]
Closing this due to inactivity
