### ISSUE TITLE
Conditional parameters don't seem to work with localised strings 

### ISSUE THREAD

**Issue by Jelle-elaut** [jovotech/jovo-framework#572]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When adding a conditional parameter (https://www.jovo.tech/docs/output/speechbuilder#conditions) to a localized string using this.speechBuilder().addT() the project won't run correctly

## Current Behavior

Compilation issues, see error log

### Error log
TypeError: this.options.overloadTranslationOptionHandler is not a function
    at Translator.translate (/Users/jelle/Development/Bitbucket/random-project-name-here/node_modules/i18next/dist/commonjs/Translator.js:98:30)
    at I18n.t (/Users/jelle/Development/Bitbucket/random-project-name-here/node_modules/i18next/dist/commonjs/i18next.js:360:73)
    at Jovo.t (/Users/jelle/Development/Bitbucket/random-project-name-here/node_modules/jovo-framework/lib/jovo.js:793:32)
    at GoogleActionSpeechBuilder.addT (/Users/jelle/Development/Bitbucket/random-project-name-here/node_modules/jovo-framework/lib/platforms/speechBuilder.js:167:33)
    at Jovo.Default Welcome Intent (/Users/jelle/Development/Bitbucket/random-project-name-here/app/app.js:86:14)
    at Handler.toIntent (/Users/jelle/Development/Bitbucket/random-project-name-here/node_modules/jovo-framework/lib/handler.js:164:54)
    at Jovo.toIntent (/Users/jelle/Development/Bitbucket/random-project-name-here/node_modules/jovo-framework/lib/jovo.js:745:22)
    at Jovo.LAUNCH (/Users/jelle/Development/Bitbucket/random-project-name-here/app/app.js:68:14)
    at Promise (/Users/jelle/Development/Bitbucket/random-project-name-here/node_modules/jovo-framework/lib/handler.js:62:36)
    at new Promise (<anonymous>)

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System:

**Comment by aswetlow** [comment]
Hey @Jelle-elaut!

(Sorry for the late reply, I was on vacation :))

Do you use Version 1 of the Jovo-Framework?

**Comment by aswetlow** [comment]
Closing this due to inactivity. Please reopen if the issue persists
