### ISSUE TITLE
 Unexpected end of JSON input : While launching jovo debugger

### ISSUE THREAD

**Issue by PrithviMukesh** [jovotech/jovo-framework#599]
## I'm submitting a...
- [ ] Bug report

## Expected Behavior

The Jovo debugger should open properly

## Current Behavior
Unable to launch the jovo debugger

### Error log
```
When I launch the jovo debugger I'm getting the below error
 SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at Conversation.sendToServer (D:\My-Task\Jovo\HelloWorld\node_modules\jovo-core\src\Conversation.ts:153:22)
      at process._tickCallback (internal/process/next_tick.js:68:7)

## Your Environment
* Jovo Framework version used: 2.2.12
* Operating System:Windows 10

**Comment by aswetlow** [comment]
Does it happen on opening the page or clicking on any of the "request buttons"?

**Comment by PrithviMukesh** [comment]
On clicking LAUNCH this error happening

**Comment by aswetlow** [comment]
How do you launch the app?
Does it also happen with the plain hello-world template?

**Comment by aswetlow** [comment]
Closing this due to inactivity. Please reopen if the issue persists.

**Comment by sahilally** [comment]
Facing the same issue in the hello world template

**Comment by aswetlow** [comment]
Unfortunately, I can't reproduce. 

Can you provide the steps you took?
