### ISSUE TITLE
after jovo run - it's showing error Message:   app.setAlexaHandler is not a function 

### ISSUE THREAD

**Issue by siddharthaweb** [jovotech/jovo-framework#641]
## I'm submitting a...

- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

**update jovo to latest version, details below**
Jovo CLI Version: 2.2.12
Jovo packages of current project:
  jovo-cms-i18next: 2.2.19
  jovo-core: 2.2.18
  jovo-db-filedb: 2.2.18
  jovo-framework: 2.2.25
  jovo-platform-alexa: 2.2.28
  jovo-platform-dialogflow: 2.2.21
  jovo-platform-googleassistant: 2.2.25
  jovo-plugin-debugger: 2.2.20
**my code**
filename - src/app.js

`const alexaHandlers = {};
_.extend(alexaHandlers,
    build_in_handlers.alexa,    
    can_fullfill.alexa,
);
app.setAlexaHandler(alexaHandlers);
const googleAssistantHandlers = {};

_.extend(googleAssistantHandlers,
    build_in_handlers.google,
    can_fullfill.google,
);
app.setGoogleAssistantHandler(googleAssistantHandlers);

module.exports.app = app;`

before run jovo update everything looks good
### Error log
```
Environment: localdev
Reading file: D:\jovo\smart-speaker\data\CompanyNamesWithTypes.csv
  
  Error -----------------------------------------------------------------

  Message:
  app.setAlexaHandler is not a function

  Stack:
  TypeError: app.setAlexaHandler is not a function
      at Object.<anonymous> (D:\jovo\smart-speaker\src\app.js:84:5)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Module.require (internal/modules/cjs/loader.js:692:17)
      at require (internal/modules/cjs/helpers.js:25:18)
      at Object.<anonymous> (D:\jovo\smart-speaker\src\index.js:5:17)
      at Module._compile (internal/modules/cjs/loader.js:778:30)

  Hint:
  This might be an issue with upgrading the Jovo packages. Try to run `jovo update` instead of `npm install`

  Learn more:
  https://www.jovo.tech/docs/installation/upgrading
```

## Your Environment

* Jovo Framework version used: 2.2.12
* Operating System: windows10

**Comment by aswetlow** [comment]
Hey, try to remove:
`/node_modules/`
`package-lock.json`

And re-install the npm packages: `npm i`

**Comment by siddharthaweb** [comment]
issue still exist
