### ISSUE TITLE
Add setBixbyHandler to support platform-specific handlers

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#668]
## I'm submitting a...

- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Jovo already supports platform-specific handlers for Alexa & Google:
https://www.jovo.tech/docs/routing#platform-handlers

Please add support for Bixby too.

## Current Behavior

The pre-release implementation for Bixby doesn't support this.
Should just be a change to `jovo-platform-bixby` files:
- src/Bixby.tx
- src/index.tx

### Error log
```
TypeError: app.setBixbyHandler is not a function
    at Object.<anonymous> (C:\dev\voice\myco\myco-voice-myapp\src\app.js:104:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\dev\voice\soar\soar-voice-soaruplift\src\index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

## Your Environment

* Jovo Framework version used: 2.2.30
* Operating System: Windows 10

**Comment by rmtuckerphx** [comment]
@rubenaeg Let me know when this is implemented in a published v3.x of jovo-framework so I can stop using the changes I made locally. Thanks!

**Comment by rubenaeg** [comment]
Implemented and published!
