### ISSUE TITLE
Cannot read property 'locale' of undefined when jovo get

### ISSUE THREAD

**Issue by Rikonorus** [jovotech/jovo-framework#683]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

all should work properly

## Current Behavior

**project.js**
```
module.exports = {
  defaultStage: 'dev',
  stages: {
    ...
    prod: {
      googleAction: {
        dialogflow: {
          projectId: 'prod-project-id',
          keyFile: './src/prod-key-file.json',
          endpoint: 'https://prod-webhook',
        },
      }
    },
  },
};
```
I do:
`> DEBUG=* VERBOSE=* jovo get googleAction --build --reverse --debug`
and have
```
Error: There was a problem:
TypeError: Cannot read property 'locale' of undefined
```

I have debugged it and found error place:
_/home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/dist/commands/get.js_
```
                _.merge(config, {
                    locales: project.getLocales(args.options.locale),
                    targets: project.getTargets('get', args.options.target, args.options.stage),
                    stage: project.getStage(args.options.stage),
                });
```

`args` at that place looks like
```
{
  "platform": "googleAction"
}
```

### Error log
```
> DEBUG=* VERBOSE=* jovo get googleAction --build --reverse --debug

  @oclif/config reading core plugin /home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli +0ms
  @oclif/config loadJSON /home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/package.json +0ms
  @oclif/config loadJSON /home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/oclif.manifest.json +2ms
  @oclif/config:jovo-cli using manifest from /home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson /home/rikonorus/.local/share/jovo-cli/package.json +0ms
  @oclif/config loadJSON /home/rikonorus/.local/share/jovo-cli/package.json +2ms
  @oclif/config loading plugins [ '@oclif/plugin-help' ] +1ms
  @oclif/config reading core plugin /home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/node_modules/@oclif/plugin-help/package.json +1ms
  @oclif/config loadJSON /home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +1ms
  @oclif/config:@oclif/plugin-help using manifest from /home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config config done +2ms
  @oclif/config start init hook +1ms
  jovo-cli:jovo-cli:hooks:init start /home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/dist/hooks/ProjectHook +0ms
  jovo-cli:jovo-cli:hooks:init start /home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/dist/hooks/VersionHook +214ms
  jovo-cli:jovo-cli:hooks:init done +285ms
  jovo-cli:jovo-cli:hooks:init done +16ms
  @oclif/config init hook done +515ms
  jovo-cli init version: @oclif/command@1.5.19 argv: [ 'get', 'googleAction', '--build', '--reverse', '--debug' ] +0ms
  @oclif/config runCommand get [ 'googleAction', '--build', '--reverse', '--debug' ] +3ms
  @oclif/config:jovo-cli require /home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/dist/commands/get.js +523ms
  @oclif/config start prerun hook +2ms
  @oclif/config prerun hook done +0ms
  jovo-cli:get init version: @oclif/command@1.5.19 argv: [ 'googleAction', '--build', '--reverse', '--debug' ] +0ms
? Found existing project files. How to proceed? Overwrite
Error: There was a problem:
TypeError: Cannot read property 'locale' of undefined
    at Object.error (/home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/node_modules/@oclif/errors/lib/index.js:22:17)
    at Get.error (/home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/node_modules/@oclif/command/lib/command.js:57:23)
    at Get.run (/home/rikonorus/.nvm/versions/node/v10.18.0/lib/node_modules/jovo-cli/dist/commands/get.js:102:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! jovo-sample-voice-app-nodejs@2.0.2 someTest: `DEBUG=* VERBOSE=* jovo get googleAction --build --reverse --debug`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the jovo-sample-voice-app-nodejs@2.0.2 someTest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

## Your Environment

* Jovo Framework version used: 3.0.1 
* Operating System: linux-x64 node-v10.18.0

**Comment by rubenaeg** [comment]
What version of the Jovo CLI are you using? You can check the version with `jovo -v`.

**Comment by rubenaeg** [comment]
We just published a new version that should fix the error, can you confirm?

**Comment by Rikonorus** [comment]
I had used jovo-cli@3.0.1.
I have checked with 3.0.2 and it works.
Thank you!
