### ISSUE TITLE
Help with DialogflowNLU - credentials file not read

### ISSUE THREAD

**Issue by Mistic92** [jovotech/jovo-framework#719]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ X ] Other... Please describe:

I'm having trouble to use DialogflowNLU with Facebook Messenger. I'm running example code but I'm getting error

```
  Error -----------------------------------------------------------------

  Code:
  ERR_PLUGIN

  Message:
  Can not access Dialogflow-API, because:
  No valid project-id was given.
  No authentication-token was provided.

  Stack:
  Error: Can not access Dialogflow-API, because:
  No valid project-id was given.
  No authentication-token was provided.
      at DialogflowNlu.naturalLanguageProcessing (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-nlu-dialogflow/src/DialogflowNlu.ts:249:13)
      at DialogflowNlu.nlu (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-nlu-dialogflow/src/DialogflowNlu.ts:121:29)
      at Middleware.run (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-core/src/core/Middleware.ts:85:20)
      at FacebookMessenger.nlu (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-platform-facebookmessenger/src/FacebookMessenger.ts:222:36)
      at Middleware.run (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-core/src/core/Middleware.ts:85:20)
      at App.handle (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-core/src/core/BaseApp.ts:259:37)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 0)
      at App.jovo_core_1.BaseApp.handle (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-platform-facebookmessenger/src/FacebookMessenger.ts:320:9)
      at App.handle (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-framework/src/App.ts:332:5)

  Module:
  DialogflowNlu

   ----------------------------------------------------------------------
```

I was trying to move credentials file to the same directory as js files, I was trying to give projectId but nothing is working. Also I found that there should be an error when I'm not passing credentialsFile path but it's not happening. 

https://github.com/jovotech/jovo-framework/blob/master/jovo-integrations/jovo-nlu-dialogflow/src/DialogflowNlu.ts#L199

What should I change? I have credentials file generated as json for service account. 

Jovo: 3.0.13
System: WSL2 on Win10

**Comment by aswetlow** [comment]
Ok, that bug occurred after a refactoring.

Fixed it. Please run `jovo update`

Btw. I recommend using the project-helper from app.getProject()

```
new DialogflowNlu({
		credentialsFile: app.getProject().getProjectPath() + '/credentials.json',
	})
```

**Comment by Mistic92** [comment]
Thanks, it's working now :)
