### ISSUE TITLE
Chatbase plugin does not work as expected

### ISSUE THREAD

**Issue by davidmatilla17** [jovotech/jovo-framework#731]
## I'm submitting a...

- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I'm having some errors using the Chatbase's plugin with jovo framework. On Alexa work well and track the intents properly but on Google Assistant crashes. 

## Current Behavior
When i launch the app on Google Assistant enter correctly on the launch function and track well but when i execute any other intent crashes. The error seems that it could not find the name of the intent that it's called.

I have a separate class for alexa intent and google assistant. 
### Error log
```
 Error -----------------------------------------------------------------

  Message:
  Cannot read property 'intent' of undefined

  Stack:
  TypeError: Cannot read property 'intent' of undefined
      at ChatbaseGoogleAssistant.createChatbaseData (D:\Projects\jovoapp\node_modules\jovo-analytics-chatbase\src\ChatbaseGoogleAssistant.ts:56:44)
      at ChatbaseGoogleAssistant.track (D:\Projects\jovoapp\node_modules\jovo-analytics-chatbase\src\ChatbaseGoogleAssistant.ts:45:25)
      at App.emit (events.js:228:7)
      at Middleware.run (D:\Projects\jovoapp\node_modules\jovo-core\src\core\Middleware.ts:89:19)
      at App.handle (D:\Projects\jovoapp\node_modules\jovo-core\src\core\BaseApp.ts:291:7)
      at App.handle (D:\Projects\jovoapp\node_modules\jovo-framework\src\App.ts:332:5)
      at D:\Projects\jovoapp\src\index.js:20:9

   ----------------------------------------------------------------------


  Request details:
  this.$googleAction initialized
  this.$type: {"type":"INTENT"}
  this.$session.$data : {}
  this.$nlu : {"intent":{"name":"WelcomeIntent"}}
  this.$inputs : {}


   ----------------------------------------------------------------------

## Your Environment
* Jovo Framework version used: 3.0.13
* Chatbase plugin version used: 3.0.13

**Comment by aswetlow** [comment]
Hey @davidmatilla17 
Thank you. @KaanKC is working on a fix.
