### ISSUE TITLE
Using `npx jovo` TypeScript project not bundling - multiple issues with the gulpfile.js build-ts

### ISSUE THREAD

**Issue by samlawski** [jovotech/jovo-framework#784]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Running `jovo deploy --target zip` or `npm run bundle` should generate a  bundle.zip file. Unfortunately, in my Jovo project I had a series of errors to resolve until it actually worked. 

Important note in the beginning: After some time, I was able to resolve the issue for my project. I'm reporting this because it took me quite a while to understand why some of these errors were happening, and they can all probably be avoided in the first place.

## Current Behavior

I'm going to describe step by step what I did, what error I got and how I was able to resolve it. Each is probably an issue on its own. But because it all relates to the overall issue that `jovo deploy --target zip` does not work for TypeScript projects out of the box I hope having just one issue ticket is fine. 

### gulp-run-command package missing

Running `npm run bundle` or specifically: 

```
gulp --gulpfile node_modules/jovo-framework/gulpfile.js build-ts --cwd ./
```

will result in the following issue: 

```
Error: Cannot find module 'gulp-run-command'
```

### `exclude` key must exist in tsconfig.json 

After installing `gulp-run-command` manually to the project, `npm run bundle` will result in this error: 

```
[08:37:47] Using gulpfile ~/[... project path ...]/node_modules/jovo-framework/gulpfile.js
[08:37:47] Starting 'build-ts'...
[08:37:47] Starting 'createTempTsConfig'...
[08:37:47] 'createTempTsConfig' errored after 952 μs
[08:37:47] TypeError: Cannot read property 'push' of undefined
    at createTempTsConfig (/[... project path ...]/node_modules/jovo-framework/gulpfile.js:81:22)
    at bound (domain.js:429:14)
    at runBound (domain.js:442:12)
    at asyncRunner (/[... project path ...]/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[08:37:47] 'build-ts' errored after 2.59 ms
```

To fix that I had to add `"exclude": []` to my _tsconfig.json_. 

### `tsc` must exist as script in package.json

That resulted in the following error: 

```
[08:39:50] Using gulpfile ~/[... project path ...]/node_modules/jovo-framework/gulpfile.js
[08:39:50] Starting 'build-ts'...
[08:39:50] Starting 'createTempTsConfig'...
[08:39:50] Finished 'createTempTsConfig' after 1.14 ms
[08:39:50] Starting 'compileTs'...
npm ERR! missing script: tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sam/.npm/_logs/2020-07-14T06_39_51_202Z-debug.log
[08:39:51] 'compileTs' errored after 228 ms
[08:39:51] Error: Non-zero exit code of "1"
    at ChildProcess.<anonymous> (/[... project path ...]/node_modules/gulp-run-command/index.es5.js:120:15)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:547:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[08:39:51] 'build-ts' errored after 231 ms
```

I fixed that by adding the line `"tsc": "tsc"` to the `scripts` section in my package.json file.

## Your Environment

* node v13.13.0
* Jovo Framework version used: 3.0.13
* Jovo CLI: 3.0.8
* Operating System: macOS 10.14.6

packages before fixing the issues: 

```
"dependencies": {
    "ask-cli": "^1.7.23",
    "axios": "^0.19.2",
    "jovo-cms-i18next": "^3.0.13",
    "jovo-core": "^3.0.13",
    "jovo-db-filedb": "^3.0.13",
    "jovo-framework": "^3.0.13",
    "jovo-platform-alexa": "^3.0.13",
    "jovo-platform-dialogflow": "^3.0.13",
    "jovo-platform-googleassistant": "^3.0.13",
    "jovo-plugin-debugger": "^3.0.13"
  },
  "devDependencies": {
    "@types/express": "^4.17.6",
    "@types/jest": "^26.0.0",
    "@types/node": "^13.13.4",
    "@types/socket.io-client": "^1.4.32",
    "axios-mock-adapter": "^1.18.1",
    "gulp": "^4.0.0",
    "gulp-install": "^1.1.0",
    "gulp-zip": "^4.2.0",
    "jest": "^26.0.1",
    "jovo-cli": "^3.0.8",
    "ts-jest": "^26.1.0",
    "typescript": "^3.8.3"
  },
```

**Comment by aswetlow** [comment]
Hey @samlawski 

Thank you for the detailed explanation.  I tried to reproduce it with a simple helloworld example, but it works as expected.

```shell
jovo new gulptest --typescript
cd gulptest
jovo deploy --target zip // no errors
npm run bundle // no errors
```

**Comment by samlawski** [comment]
Thanks for the response. Interesting!

I just did the same steps as you just using `npx` because I don't have the CLI installed globally. Maybe that could be the reason?

```
npx jovo new projectname --typscript
cd projectname
```

And then: 

```shell
$ npx jovo deploy --target zip
npx: Installierte 125 in 4.204s
I'm setting everything up
$ npm run bundle

> jovo-sample-voice-app-nodejs@2.0.1-alpha.2 bundle /Users/sam/projectname
> gulp --gulpfile node_modules/jovo-framework/gulpfile.js --cwd ./

Error: Cannot find module 'gulp-run-command'
Require stack:
- /Users/sam/projectname/node_modules/jovo-framework/gulpfile.js
- /Users/sam/projectname/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js
- /Users/sam/projectname/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
- /Users/sam/projectname/node_modules/gulp/node_modules/gulp-cli/index.js
- /Users/sam/projectname/node_modules/gulp/bin/gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/sam/projectname/node_modules/jovo-framework/gulpfile.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/sam/projectname/node_modules/jovo-framework/gulpfile.js',
    '/Users/sam/projectname/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js',
    '/Users/sam/projectname/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js',
    '/Users/sam/projectname/node_modules/gulp/node_modules/gulp-cli/index.js',
    '/Users/sam/projectname/node_modules/gulp/bin/gulp.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jovo-sample-voice-app-nodejs@2.0.1-alpha.2 bundle: `gulp --gulpfile node_modules/jovo-framework/gulpfile.js --cwd ./`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jovo-sample-voice-app-nodejs@2.0.1-alpha.2 bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sam/.npm/_logs/2020-07-14T11_31_13_426Z-debug.log
```

Error logs: 

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.13.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'bundle'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.13.0
4 verbose run-script [ 'prebundle', 'bundle', 'postbundle' ]
5 info lifecycle jovo-sample-voice-app-nodejs@2.0.1-alpha.2~prebundle: jovo-sample-voice-app-nodejs@2.0.1-alpha.2
6 info lifecycle jovo-sample-voice-app-nodejs@2.0.1-alpha.2~bundle: jovo-sample-voice-app-nodejs@2.0.1-alpha.2
7 verbose lifecycle jovo-sample-voice-app-nodejs@2.0.1-alpha.2~bundle: unsafe-perm in lifecycle true
8 verbose lifecycle jovo-sample-voice-app-nodejs@2.0.1-alpha.2~bundle: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/sam/projectname/node_modules/.bin:/Users/sam/.rvm/gems/ruby-2.7.0/bin:/Users/sam/.rvm/gems/ruby-2.7.0@global/bin:/Users/sam/.rvm/rubies/ruby-2.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/sam/dev/google-cloud-sdk/bin:/Users/sam/.rvm/gems/ruby-2.7.0/bin:/Users/sam/.rvm/gems/ruby-2.7.0@global/bin:/Users/sam/.rvm/rubies/ruby-2.7.0/bin:/Users/sam/.rvm/bin
9 verbose lifecycle jovo-sample-voice-app-nodejs@2.0.1-alpha.2~bundle: CWD: /Users/sam/projectname
10 silly lifecycle jovo-sample-voice-app-nodejs@2.0.1-alpha.2~bundle: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'gulp --gulpfile node_modules/jovo-framework/gulpfile.js --cwd ./'
10 silly lifecycle ]
11 silly lifecycle jovo-sample-voice-app-nodejs@2.0.1-alpha.2~bundle: Returned: code: 1  signal: null
12 info lifecycle jovo-sample-voice-app-nodejs@2.0.1-alpha.2~bundle: Failed to exec bundle script
13 verbose stack Error: jovo-sample-voice-app-nodejs@2.0.1-alpha.2 bundle: `gulp --gulpfile node_modules/jovo-framework/gulpfile.js --cwd ./`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid jovo-sample-voice-app-nodejs@2.0.1-alpha.2
15 verbose cwd /Users/sam/projectname
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/13.13.0_1/bin/node" "/usr/local/bin/npm" "run" "bundle"
18 verbose node v13.13.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error jovo-sample-voice-app-nodejs@2.0.1-alpha.2 bundle: `gulp --gulpfile node_modules/jovo-framework/gulpfile.js --cwd ./`
22 error Exit status 1
23 error Failed at the jovo-sample-voice-app-nodejs@2.0.1-alpha.2 bundle script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```


This is my package JSON without any changes: 

```
{
  "name": "jovo-sample-voice-app-nodejs",
  "version": "2.0.1-alpha.2",
  "description": "A sample voice app that works with the Jovo Framework",
  "main": "src/index.js",
  "dependencies": {
    "jovo-db-filedb": "^2.1.0",
    "jovo-framework": "^2.1.0",
    "jovo-platform-alexa": "^2.1.0",
    "jovo-platform-googleassistant": "^2.1.0",
    "jovo-plugin-debugger": "^2.1.0"
  },
  "devDependencies": {
    "gulp": "^4.0.0",
    "gulp-install": "^1.1.0",
    "gulp-zip": "^4.2.0"
  },
  "scripts": {
    "start": "node index.js --webhook",
    "tsc": "node -v",
    "test": "echo \"Error: no test specified\"",
    "bundle": "gulp --gulpfile node_modules/jovo-framework/gulpfile.js --cwd ./"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jovotech/jovo-sample-voice-app-nodejs.git"
  },
  "author": "Jovo",
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/jovotech/jovo-sample-voice-app-nodejs/issues"
  },
  "homepage": "https://github.com/jovotech/jovo-sample-voice-app-nodejs#readme"
}
```

**Comment by aswetlow** [comment]
Works for me.

These are my devDependencies after creating a new project.
```
"devDependencies": {
    "@types/express": "^4.17.6",
    "@types/jest": "^25.2.1",
    "@types/socket.io-client": "^1.4.32",
    "gulp": "^4.0.2",
    "gulp-install": "^1.1.0",
    "gulp-run-command": "0.0.10",
    "gulp-zip": "^5.0.1",
    "jest": "^26.0.1",
    "ts-jest": "^25.5.0",
    "tslint": "^6.1.2",
    "typescript": "^3.9.2"
  },
```

I can't see `gulp-run-command` in your package.json. `Error: Cannot find module 'gulp-run-command'` make sense now. How did you setup your project?

**Comment by samlawski** [comment]
Ok interesting. I just ran `npx jovo new projectname --typscript` without having the jovo CLI installed. That resulted in the package.json you see above.

I now installed the Jovo CLI `npm install -g jovo-cli` and then used `jovo new projectname --typescript` to create a new project instead and I get the same results as you and everything (including `npm run bundl`) works without errors. 

So the problem seems to have come when running the Jovo CLI using `npx`. Not sure why that is because I thought `npx` will just use the most current version of an NPM package. But maybe not?

**Comment by aswetlow** [comment]
I haven't used `npx` that much. We will investigate.

**Comment by aswetlow** [comment]
Hey @samlawski 
Do you still have this problem? I can't reproduce it. Even with `npx`

```
npx jovo new <project> --typescript
cd <project>
npm run bundle // works
npx jovo deploy --target zip // works
```

**Comment by aswetlow** [comment]
Closing due to inactivity. Please re-open if it still persists.
