### ISSUE TITLE
Cannot read property 'jovo-debugger' of undefined when using Progressive Response

### ISSUE THREAD

**Issue by frivas** [jovotech/jovo-framework#794]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Should not show that error.

## Current Behavior
When using progressive responses this error is shown. Sorry that the explanation is not too elaborated, because it happens only when progressive responses are used:

For example: 

```
"use strict";

const { App } = require("jovo-framework");
const { Alexa } = require("jovo-platform-alexa");
const { GoogleAssistant } = require("jovo-platform-googleassistant");
const { JovoDebugger } = require("jovo-plugin-debugger");
const { FileDb } = require("jovo-db-filedb");

// ------------------------------------------------------------------
// APP INITIALIZATION
// ------------------------------------------------------------------

const app = new App();

app.use(new Alexa(), new GoogleAssistant(), new JovoDebugger(), new FileDb());

// ------------------------------------------------------------------
// APP LOGIC
// ------------------------------------------------------------------

app.setHandler({
  LAUNCH() {
    this.$alexaSkill
      .progressiveResponse("Processing")
      .then(() => this.$alexaSkill.progressiveResponse("Still processing"));

    this.tell("Text after API call");
  },
});

module.exports = { app };

```

 

### Error log
```
Error 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'jovo-debugger' of undefined",
    "stack": [
        "TypeError: Cannot read property 'jovo-debugger' of undefined",
        "    at AlexaSkill.isJovoDebuggerRequest (/var/task/node_modules/jovo-core/dist/src/core/Jovo.js:504:36)",
        "    at AlexaSkill.progressiveResponse (/var/task/node_modules/jovo-platform-alexa/dist/src/core/AlexaSkill.js:115:18)",
        "    at AlexaSkill.LAUNCH (/var/task/app.js:24:8)",
        "    at Function.applyHandle (/var/task/node_modules/jovo-core/dist/src/plugins/Handler.js:140:43)",
        "    at handle (/var/task/node_modules/jovo-core/dist/src/plugins/Handler.js:192:23)",
        "    at async Middleware.run (/var/task/node_modules/jovo-core/dist/src/core/Middleware.js:76:21)",
        "    at async App.handle (/var/task/node_modules/jovo-core/dist/src/core/BaseApp.js:203:13)",
        "    at async App.handle (/var/task/node_modules/jovo-framework/dist/src/App.js:265:9)",
        "    at async Runtime.exports.handler (/var/task/index.js:26:3)"
    ]
}
```

## Your Environment

* Jovo Framework version used: 

```
Jovo packages of current project:
  jovo-analytics-dashbot: 3.0.24
  jovo-cli: 3.0.20
  jovo-cli-core: 3.0.5
  jovo-cli-deploy-lambda: 3.0.5
  jovo-cli-platform-alexa: 3.0.12
  jovo-cli-platform-google: 3.0.8
  jovo-cli-platform-spokestack: 3.0.3
  jovo-cms-i18next: 3.0.20
  jovo-config: 0.1.0
  jovo-core: 3.0.19
  jovo-db-dynamodb: 3.0.20
  jovo-db-filedb: 3.0.20
  jovo-framework: 3.0.21
  jovo-model: 0.1.14
  jovo-model-alexa: 0.1.14
  jovo-model-dialogflow: 0.1.16
  jovo-platform-alexa: 3.0.25
  jovo-platform-dialogflow: 3.0.19
  jovo-platform-googleassistant: 3.0.21
  jovo-plugin-debugger: 3.0.19
  jovo-webhook-connector: 3.0.4
All packages are already up to date!
```

* Operating System: macOS Catalina 10.15.6
* NodeJS: 14.6.0

**Comment by aswetlow** [comment]
Thanks Francisco 

Fixed, preparing the updated version to be published on NPM.

**Comment by frivas** [comment]
Thank you very much Alex! Just tested it, flawless! 😄
