### ISSUE TITLE
TypeError: handleRequest.jovo.getRoute is not a function

### ISSUE THREAD

**Issue by HarkinAI** [jovotech/jovo-framework#834]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
When I send a LaunchRequest, the skill should send a valid response.

## Current Behavior
The skill throws an error and the session ends.

### Error log
```
Message:
  handleRequest.jovo.getRoute is not a function
  
  Stack:
  TypeError: handleRequest.jovo.getRoute is not a function
      at BasicLogging.routingLogger (/Users/xxx/xx/xxxx/project/node_modules/jovo-framework/src/middleware/logging/BasicLogging.ts:96:27)
      at App.emit (events.js:327:22)
      at Middleware.run (/Users/xxx/xx/xxxx/project/node_modules/jovo-framework/node_modules/jovo-core/src/core/Middleware.ts:95:21)
      at App.handle (/Users/xxx/xx/xxxx/project/node_modules/jovo-framework/node_modules/jovo-core/src/core/BaseApp.ts:271:7)
      at App.handle (/Users/xxx/xx/xxxx/project/node_modules/jovo-framework/src/App.ts:333:5)
      at /Users/xxx/xx/xxxx/project/src/index.js:20:5
  
  Hint:
  This might be an issue with upgrading the Jovo packages. Try to run `jovo update` instead of `npm install`
```
Note that I followed the hint instructions and ran 'jovo update', then tried again. I received the same error.

The stacktrace points to the index.js file, so I've included it here. Line 20 is labeled:
```
'use strict';

const { ExpressJS, Lambda, Webhook } = require('jovo-framework');
const { app } = require('./app.js');

// ------------------------------------------------------------------
// HOST CONFIGURATION
// ------------------------------------------------------------------

// ExpressJS (Jovo Webhook)
if (process.argv.indexOf('--webhook') > -1) {
  const port = process.env.JOVO_PORT || 3000;
  Webhook.jovoApp = app;

  Webhook.listen(port, () => {
    console.info(`Local server listening on port ${port}.`);
  });

  Webhook.post('/webhook', async (req, res) => {
    await app.handle(new ExpressJS(req, res));  <----------- this is line 20
  });
}

// AWS Lambda
exports.handler = async (event, context, callback) => {
  await app.handle(new Lambda(event, context, callback));
};
```

## Your Environment

* Jovo Framework version used: 3.1.3
* Operating System: MacOS Catalina 10.15.7

**Comment by HarkinAI** [comment]
I deleted my node_modules and re-installed jovo packages. Now it's working.
