### ISSUE TITLE
Jovo crashes when FB respond "sender_action:mark_seen" 400

### ISSUE THREAD

**Issue by Mistic92** [jovotech/jovo-framework#836]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior

Jovo crashes when facebook response with status 400 "mark_seen" and  and Jovo respond with 500

We are using Jovo with below schema
FB platform -> Jovo in CloudRun -> Dialogflow NLP

For now we don't have a exact reproduction steps

### Error log
```
unhandledRejection
  {}
  Error: Request failed with status code 400
      at createError (C:\Users\pelia\Documents\xxxxxxxxxx\node_modules\jovo-core\node_modules\axios\lib\core\createError.js:16:15)
      at settle (C:\Users\pelia\Documents\xxxxxxxxxx\node_modules\jovo-core\node_modules\axios\lib\core\settle.js:17:12)
      at IncomingMessage.handleStreamEnd (C:\Users\pelia\Documents\xxxxxxxxxx\node_modules\jovo-core\node_modules\axios\lib\adapters\http.js:236:11)
      at C:\Users\pelia\Documents\xxxxxxxxxx\node_modules\@google-cloud\trace-agent\build\src\cls\async-hooks.js:147:49
      at AsyncHooksCLS.runWithContext (C:\Users\pelia\Documents\xxxxxxxxxx\node_modules\@google-cloud\trace-agent\build\src\cls\async-hooks.js:125:20)
      at IncomingMessage.contextWrapper (C:\Users\pelia\Documents\xxxxxxxxxx\node_modules\@google-cloud\trace-agent\build\src\cls\async-hooks.js:147:25)
      at IncomingMessage.emit (events.js:215:7)
      at endReadableNT (_stream_readable.js:1183:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
  {"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (C:\\Users\\pelia\\Documents\\xxxxxxxxxx\\node_modules\\jovo-core\\node_modules\\axios\\lib\\core\\createEr
ror.js:16:15)\n    at settle (C:\\Users\\pelia\\Documents\\xxxxxxxxxx\\node_modules\\jovo-core\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\pelia\\Documents\\xxxxxxxxxx\\node_modules\\j
ovo-core\\node_modules\\axios\\lib\\adapters\\http.js:236:11)\n    at C:\\Users\\pelia\\Documents\\xxxxxxxxxx\\node_modules\\@google-cloud\\trace-agent\\build\\src\\cls\\async-hooks.js:147:49\n    at AsyncHooksCLS.runWithContext (C:\\Users\\peli
a\\Documents\\xxxxxxxxxx\\node_modules\\@google-cloud\\trace-agent\\build\\src\\cls\\async-hooks.js:125:20)\n    at IncomingMessage.contextWrapper (C:\\Users\\pelia\\Documents\\xxxxxxxxxx\\node_modules\\@google-cloud\\trace-agent\\build\\src\
\cls\\async-hooks.js:147:25)\n    at IncomingMessage.emit (events.js:215:7)\n    at endReadableNT (_stream_readable.js:1183:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"url":"https://graph.facebook.com/v
8.0/me/messages?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","method":"post",
"data":"{\"recipient\":{\"id\":\"2909252735850718\"},\"sender_action\":\"mark_seen\"}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.19.2","Content-Length":67},"transformRequest":[nu
ll],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}
```

## Your Environment

* Jovo Framework version used: 
```jovo-analytics-googleanalytics: 3.1.0
  jovo-core: 3.1.0
  jovo-db-filedb: 3.1.0
  jovo-db-firestore: 3.1.0
  jovo-framework: 3.1.0
  jovo-nlu-dialogflow: 3.1.0
  jovo-platform-dialogflow: 3.1.0
  jovo-platform-facebookmessenger: 3.1.0
  jovo-plugin-class-handler: 2.0.1
  jovo-plugin-debugger: 3.1.0
```

* Operating System:Windows 10

**Comment by m-ripper** [comment]
Hello @Mistic92,

thanks for the bug-report. 

I've tested the following:
```
if(this.$messengerBot) {
      try {
        const res = await this.$messengerBot.showAction(SenderActionType.MarkSeen);
        console.log(res?.data);
      } catch (e) {
        if(e.isAxiosError) {
          console.log(e.response?.data);
        } else {
          console.log(e);
        }
      }
}
```
And for me, no error was thrown and the message was marked as seen.

With the code above you should be able to catch the error and retrieve a more detailed error-message. \
It could be possible that your page-access-token has expired, I recommend checking out [this tool](https://developers.facebook.com/tools/debug/accesstoken/) to validate your access-token.

In case your page-access-token has expired I recommend checking out [this page](https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing/) for more information, how to retrieve long-lived access-tokens.

Please let me know if this error still occurs even if the page-access-token is valid.

**Comment by Mistic92** [comment]
Looks like we had message ack in code in completely other place which was causing issue.
