### ISSUE TITLE
Trying to run a new jovo project results in a ERR_CRYPTO_OPERATION_FAILED error

### ISSUE THREAD

**Issue by dantman** [jovotech/jovo-framework#885]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

- Running Jovo according to the Quickstart should work

## Current Behavior

Running `jovo new <project>` then `jovo run` ends up with an error.

### Error log

```
 jovo run: Runs a local development server (webhook).
   >> Learn more: https://jovo.tech/docs/cli/run

Sorry, there seems to be an issue with the connection!
Error: xhr poll error
    at XHR.Transport.onError (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transport.js:68:13)
    at Request.<anonymous> (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transports/polling-xhr.js:132:10)
    at Request.Emitter.emit (/Users/daniel/Workspace/anivoice/node_modules/component-emitter/index.js:145:20)
    at Request.onError (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transports/polling-xhr.js:314:8)
    at Timeout._onTimeout (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transports/polling-xhr.js:274:12)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  type: 'TransportError',
  description: Error: Unable to load PFX certificate
      at Object.createSecureContext (node:_tls_common:333:17)
      at Object.connect (node:_tls_wrap:1601:48)
      at Agent.createConnection (node:https:130:22)
      at Agent.createSocket (node:_http_agent:323:26)
      at Agent.addRequest (node:_http_agent:274:10)
      at new ClientRequest (node:_http_client:314:16)
      at Object.request (node:https:326:10)
      at Object.<anonymous> (/Users/daniel/Workspace/anivoice/node_modules/agent-base/patch-core.js:25:22)
      at /Users/daniel/Workspace/anivoice/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20
      at XMLHttpRequest.send (/Users/daniel/Workspace/anivoice/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js:495:17) {
    code: 'ERR_CRYPTO_OPERATION_FAILED'
  }
}
Local server listening on port 3000.
  Sorry, there seems to be an issue with the connection!
Sorry, there seems to be an issue with the connection!
Error: xhr poll error
    at XHR.Transport.onError (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transport.js:68:13)
    at Request.<anonymous> (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transports/polling-xhr.js:132:10)
    at Request.Emitter.emit (/Users/daniel/Workspace/anivoice/node_modules/component-emitter/index.js:145:20)
    at Request.onError (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transports/polling-xhr.js:314:8)
    at Timeout._onTimeout (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transports/polling-xhr.js:274:12)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  type: 'TransportError',
  description: Error: Unable to load PFX certificate
        at Object.createSecureContext (node:_tls_common:333:17)
      at Object.connect (node:_tls_wrap:1601:48)
      at Agent.createConnection (node:https:130:22)
      at Agent.createSocket (node:_http_agent:323:26)
      at Agent.addRequest (node:_http_agent:274:10)
      at new ClientRequest (node:_http_client:314:16)
      at Object.request (node:https:326:10)
      at Object.<anonymous> (/Users/daniel/Workspace/anivoice/node_modules/agent-base/patch-core.js:25:22)
      at /Users/daniel/Workspace/anivoice/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20
      at XMLHttpRequest.send (/Users/daniel/Workspace/anivoice/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js:495:17) {
    code: 'ERR_CRYPTO_OPERATION_FAILED'
  }
}
  Sorry, there seems to be an issue with the connection!

To open Jovo Debugger in your browser, enter .
  Sorry, there seems to be an issue with the connection!
Sorry, there seems to be an issue with the connection!
Error: xhr poll error
    at XHR.Transport.onError (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transport.js:68:13)
    at Request.<anonymous> (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transports/polling-xhr.js:132:10)
    at Request.Emitter.emit (/Users/daniel/Workspace/anivoice/node_modules/component-emitter/index.js:145:20)
    at Request.onError (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transports/polling-xhr.js:314:8)
    at Timeout._onTimeout (/Users/daniel/Workspace/anivoice/node_modules/engine.io-client/lib/transports/polling-xhr.js:274:12)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  type: 'TransportError',
  description: Error: Unable to load PFX certificate
      at Object.createSecureContext (node:_tls_common:333:17)
      at Object.connect (node:_tls_wrap:1601:48)
      at Agent.createConnection (node:https:130:22)
      at Agent.createSocket (node:_http_agent:323:26)
      at Agent.addRequest (node:_http_agent:274:10)
      at new ClientRequest (node:_http_client:314:16)
      at Object.request (node:https:326:10)
      at Object.<anonymous> (/Users/daniel/Workspace/anivoice/node_modules/agent-base/patch-core.js:25:22)
      at /Users/daniel/Workspace/anivoice/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20
      at XMLHttpRequest.send (/Users/daniel/Workspace/anivoice/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js:495:17) {
    code: 'ERR_CRYPTO_OPERATION_FAILED'
  }
}
```

## Your Environment

* Node.js: v15.5.0
* NPM: 6.14.10
* Jovo Framework version used: 3.3.0
* Operating System: macOS Catalina 10.15.7

**Comment by aswetlow** [comment]
Hey @dantman 

Node 15 is currently not supported. Switching to Node 14 or below will fix your issue.
